### ISSUE TITLE
Logger Error

### ISSUE THREAD

**Issue by TorresRC** [gem-pasteur/PanACoTA#1]
Is there an error in your annotate_module related with the log:
ERROR  'Logger' object has no attribute 'details'

**Comment by asetGem** [comment]
Hi!
Could you give me the command you used to get this kind of error?

**Comment by TorresRC** [comment]
Sure:

$PanACoTA annotate -r ~/Temp/Panacota/FromNCBI/Annotation -n HEPY --info ~/Temp/Panacota/FromNCBI/LSTINFO-210-filtered-0.0001_0.06.txt --threads 8 --annot_dir ~/Temp/Panacota/FromNCBI/Annotation

Thanks,
Roberto

**Comment by asetGem** [comment]
It's very difficult to know what happened like this...
Could you send me your info file, the PanACoTA log, and eventually, if possible 1 or 2 of your genomes so that I can try to reproduce the error?

**Comment by asetGem** [comment]
Does it work now?
