### ISSUE TITLE
query/target coverage

### ISSUE THREAD

**Issue by ramiroricardo** [gem-pasteur/PanACoTA#10]
Hi Amandine,

I was wondering about query/target coverage in panacota. From the paper it seems to be set at 80%. Though
is there an option to adjust this? (I don't see it when i call `PanACoTA pangenome -h`)

Thanks,

Ramiro

**Comment by asetGem** [comment]
Hi,
Yes, it has been fixed to 80% in PanACoTA. As this almost always the value used, we did not provide an option to change it. However, if you think it is relevant, we could add this option in a next version. Let me know if you need to change this value.
