### ISSUE TITLE
PanACoTA all skips cutn parametr

### ISSUE THREAD

**Issue by oxygen311** [gem-pasteur/PanACoTA#11]
Hello!

When I'm running `PanACoTA all` all module, it ignores `cutn` parameter and splits genomes with 5 `N` anyway, command:
```bash
PanACoTA all -o Yersinia_pestis --cutn 100 -n YEPE --threads 32 -t 632 -l 'complete,chromosome' --l90 1 --soft iqtree2
```

I tried to pass `cutn` parameter in the config file, the problem stays the same. Also, it seems to ignore `l90` passed in config file.

Running mostly same command but only with  `PanACoTA prepare` module works great:
```bash
PanACoTA prepare -o Yersinia_pestis --cutn 100 --threads 8 -T 632 -l 'complete,chromosome' --l90 1
```

**Comment by asetGem** [comment]
Hello!

Thanks, indeed, there was a problem, as these parameters were re-defined by the 'annotate' section of the config file. I made a modification on the master branch. Can you try it please? And if it works, I will do a new release.

**Comment by oxygen311** [comment]
Seems to work OK, thanks for the fix!

I'm not sure it worth mentioning, but for some reason `./make update` didn't work for me, but `./make upgrade` did. It may be a problem with a Mac OS version of `make`.

**Comment by asetGem** [comment]
Thanks for your feedback!

Yes, the command line to get a new version is `./make upgrade`. More info on how to get a new version of panacota: 
https://aperrin.pages.pasteur.fr/pipeline_annotation/html-doc/starting.html#from-github-repository

It is using the same "vocabulary" as pypi (`pip install panacota --upgrade`).

**Comment by oxygen311** [comment]
Now it says `./make update` in README.md at GitHub. I think it can be fixed for less misunderstanding.

**Comment by asetGem** [comment]
Oh yes! I forgot this one. It is now changed. Thanks a lot for pointing out!
