### ISSUE TITLE
Combining step1 and step2 on the prepare module

### ISSUE THREAD

**Issue by genomesandMGEs** [gem-pasteur/PanACoTA#12]
Hi there,

I would like to know if it's possible to combine my own assemblies (step2) plus downloading all assemblies from the same taxid as my own assemblies (step1). The goal is to create the same outputs for both collections (my assemblies + publicly available ones). 

Thanks for your time!

**Comment by asetGem** [comment]
Hi,

If I understand well your need, you can first run the `prepare` step, downloading all publicly available assemblies with your taxid. Download them (or move them after) to the same folder as your own assemblies. 

Then, just give the names of all your genomes (yours + publicly available) in the list_file as input of `annotate` step, and it will generate the same ouputs for all of them.

Does this answer to your question?

**Comment by genomesandMGEs** [comment]
Yes, that's what I need. Thanks a lot, and cool tool!
