### ISSUE TITLE
Problem with mmseq

### ISSUE THREAD

**Issue by yoshikal** [gem-pasteur/PanACoTA#14]
Hi, 

Using the `pangenome` subcommand I got this error:

`ERROR Problem while trying to convert mmseq result file to tsv file`

Do you know how to fix this problem? 

Thanks !

**Comment by asetGem** [comment]
Hi,

Can you tell me which version of PanACoTA you used please?
Thanks!

**Comment by yoshikal** [comment]
Yes, I am using version 1.2.0

**Comment by asetGem** [comment]
Can you try to install the latest version (master of github repo), and let me know if this fixed the problem?

**Comment by yoshikal** [comment]
Yes the problem is solved! Thank you !!

**Comment by asetGem** [comment]
Cool if it works, I will do a new release with this change then. Thanks for your feedback.
