### ISSUE TITLE
Bootstrapping with `PanACoTA all`

### ISSUE THREAD

**Issue by oxygen311** [gem-pasteur/PanACoTA#16]
Hello, Amandine!

I think I've found little bug while trying to add bootstraps on the tree using `PanACoTA all` command or I didn't get how to set bootstrap in that module.
`PanACoTA all` itself does not have parameters for bootstrapping, so it seems that parameters need to be passed with a config file. I've tried two variants: 
* `boot = 1000` which leads to `ERROR: boot must be a boolean. Wrong value: 1000.`
* `boot = True` which leads to `PanACoTA: error: With IQtree, number of replicates for bootstraps must be >= 1000.`

Some details:
* Full command: `PanACoTA all -o Legionella_pneumophila_test  --cutn 125 -n LEPN --threads 32 -T 446 -l 'complete,chromosome' --l90 1 --soft iqtree2 -c configfile.ini`. 
* Version: `PanACoTA - v. 1.3.0`

**Comment by asetGem** [comment]
Hello!

Thanks for pointing out. Indeed, I asked for a boolean instead of an int!
I changed this and pushed version 1.3.0-dev1 on master. Can you try and let me know if it works?

**Comment by oxygen311** [comment]
I've tested it, working great.
Thanks for fast fix and great tool!
