### ISSUE TITLE
Prokka error

### ISSUE THREAD

**Issue by ryobon-dev** [gem-pasteur/PanACoTA#19]
When I tried to run PanACoTA with an Examples file, the following error occured while an annotation step. The command I put was "PanACoTA annotate -d Examples/genomes_init -r Examples/2-res-prokka -l Examples/input_files/list_genomes.lst -n GENO --l90 3 --nbcont 10". It seems like Prokka did not work. I installed PanACoTA with conda in a dedicated conda environment.

Annotation:                               0/3 (N/A%) - Elapsed Time: 0:00:00 -   * [2021-07-15 11:18:33] : ERROR  Error while trying to run prokka on GENO.0721.00001 from Examples/2-res-prokka/tmp_files/genome1.fst_prokka-split5N.fna
Annotation: █████████                     1/3 ( 33%) - Elapsed Time: 0:00:00 -   * [2021-07-15 11:18:33] : ERROR  Error while trying to run prokka on GENO.1216.00002 from Examples/2-res-prokka/tmp_files/genome3-chromo.fst-all.fna_prokka-split5N.fna
Annotation: ███████████████████           2/3 ( 66%) - Elapsed Time: 0:00:00 -   * [2021-07-15 11:18:33] : ERROR  Error while trying to run prokka on GEN4.1111.00001 from Examples/2-res-prokka/tmp_files/genome4.fst_prokka-split5N.fna
Annotation: █████████████████████████████ 3/3 (100%) - Elapsed Time: 0:00:00 -
  * [2021-07-15 11:18:33] : ERROR  Error: No genome was correctly annotated, no need to format them.

**Comment by asetGem** [comment]
Hi!

Can you tell me which version of PanACoTA you used please?
Also, looking in the .`log.details` file, can you run one of the prokka commands, and see why prokka does not work?

**Comment by ryobon-dev** [comment]
Hello,

 

I used v.1.1.0.

 

In the log, “Error while trying to run prokka” was shown.

 

Good thing for me is that I could run PanACoTA with different PC. The issue might be machine depended.

 

Thanks,

 

Tomtoada

**Comment by asetGem** [comment]
I think that this is a problem with conda installing incompatible dependences for prokka (see #9 ). This problem has been solved with the release of version 1.2.0. Let me know if it still does not work for you once you have upgraded to version 1.2.0

**Comment by ryobon-dev** [comment]
Thanks,
