### ISSUE TITLE
Error using annotate: unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by IsabelFE** [gem-pasteur/PanACoTA#2]
Hello,

I am getting the following error when trying to run the annotate module.

Could you help me with this? Thanks a lot!!

Isabel

`[2020-10-07 18:35:58] : INFO PanACoTA version 1.0-dev
[2020-10-07 18:35:58] : INFO Command used
> PanACoTA annotate -r Annotated_Genomes -n NCBI --info Genomes_NCBI/LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.txt
[2020-10-07 18:35:58] : INFO Reading given information on your genomes in Genomes_NCBI/LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.txt
[2020-10-07 18:35:58] : INFO Found 2 genomes in total
[2020-10-07 18:35:58] : INFO Generating distribution of L90 and #contigs graphs.
[2020-10-07 18:35:59] : INFO Renaming kept genomes according to their quality (2 genomes)
[2020-10-07 18:35:59] : INFO Annotating all genomes with prokka
Traceback (most recent call last):
File "/Users/isabelfe/opt/anaconda3/bin/PanACoTA", line 155, in 
main()
File "/Users/isabelfe/opt/anaconda3/bin/PanACoTA", line 21, in main
action(args)
File "/Users/isabelfe/opt/anaconda3/lib/python3.6/site-packages/PanACoTA/subcommands/annotate.py", line 155, in main_from_parse
arguments.small)
File "/Users/isabelfe/opt/anaconda3/lib/python3.6/site-packages/PanACoTA/subcommands/annotate.py", line 387, in main
prodigal_only, small, quiet=quiet)
File "/Users/isabelfe/opt/anaconda3/lib/python3.6/site-packages/PanACoTA/annotate_module/annotation_functions.py", line 109, in run_annotation_all
term_width=100).start()
TypeError: init() got an unexpected keyword argument 'max_value'`

**Comment by asetGem** [comment]
Hello !

Can you run `pip show progressbar2` (or pip3) and give me the output please. It seems that your version of progressbar does not accept an argument I use here.

**Comment by IsabelFE** [comment]
Hi!

I didn't have progressbar2 installed. I installed it and now the annotation is running (I have a bunch of genomes, so I guess it will take a while).

I got some errors initially with annotate not running because I was missing termcolor, progressbar, colorlog and ncbi-genome-download. I hope now I have everything I need. 

This is a great package! Our lab is getting started with Pangenomics and your workflow is really useful. 

Thanks for your help.

**Comment by asetGem** [comment]
Great if it worked :+1: 
But how did you do to install PanACoTA ? It should automatically install those packages, so that actually you don't need to install them by hand!

**Comment by IsabelFE** [comment]
git clone https://github.com/gem-pasteur/PanACoTA.git
cd PanACoTA
./make --user

**Comment by asetGem** [comment]
Do you still have the output of this command?

**Comment by IsabelFE** [comment]
Is still giving me an error with the annotation: 
Annotation:                                                    0/2 (N/A%) - Elapsed Time: 0:07:36 - Error while trying to run prokka on NCBI.1020.00002 from Genomes_NCBI/tmp_files/GCF_000175635.1_ASM17563v1_genomic.fna_prepare-split5N.fna

**Comment by IsabelFE** [comment]
> Do you still have the output of this command?

I don't think so. I can run it again

**Comment by asetGem** [comment]
> Is still giving me an error with the annotation:
> Annotation: 0/2 (N/A%) - Elapsed Time: 0:07:36 - Error while trying to run prokka on NCBI.1020.00002 from Genomes_NCBI/tmp_files/GCF_000175635.1_ASM17563v1_genomic.fna_prepare-split5N.fna

Can you look at the file `Genomes_NCBI/tmp_files/GCF_000175635.1_ASM17563v1_genomic.fna_prepare-split5N.fna-prokka.log` or `Genomes_NCBI/tmp_files/GCF_000175635.1_ASM17563v1_genomic.fna_prepare-split5N.fna-prokkaRes/NCBI.1020.00002.log` if prokka reported an error while running?

**Comment by IsabelFE** [comment]
[GCF_000175635.1_ASM17563v1_genomic.fna_prepare-split5N.fna-prokka.log](https://github.com/gem-pasteur/PanACoTA/files/5348728/GCF_000175635.1_ASM17563v1_genomic.fna_prepare-split5N.fna-prokka.log)
[NCBI.1020.00002.log](https://github.com/gem-pasteur/PanACoTA/files/5348731/NCBI.1020.00002.log)

**Comment by asetGem** [comment]
It seems that you did not install prokka properly. Here, prokka crashes because it cannot find `tbl2asn`. As it crashes, PanaCoTA gives you an error message to inform that it could not be annotated.

**Comment by asetGem** [comment]
Maybe you could send an issue on prokka's github, saying that your annotation did not work, attaching this log file. It seems that prokka detects tbl2asn, but then cannot run it. So, maybe they have an idea on why?

**Comment by IsabelFE** [comment]
I am trying to reinstall everything. The funny thing is that I used prokka last week without any issue, but now I wanted to use it inside your pipeline in order to use the contigs/L90 and mash filtering steps

**Comment by asetGem** [comment]
Did you run it on the same genome last time?

**Comment by IsabelFE** [comment]
No, it wasn't the same genome. I am installing everything fresh in a new environment and I will also check running prokka directly outside PanACota. I have to go now but I will update you later. Thanks for your help

**Comment by asetGem** [comment]
To help you run prokka outside of PanACoTA, you can find the command it used in the file `Annotated_GenomesPanACoTA-annotate_Genomes_NCBI/LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.log.details` 
You will find something like ` DETAIL :: Prokka command: ` and then the command line used.

Hope this will help you fix your problem

**Comment by IsabelFE** [comment]
I installed everything fresh in a new environment and I don't get the tbl2asn issue again. I think that all packages are in place now, but I still get a different error. I am going to open a new issue focused on the new error

**Comment by JasmineGamblin** [comment]
Hello,

I am trying to run PanACoTA from the singularity image (latest version), and I got the same error as  IsabelFE with the annotate module "could not run command: tbl2asn". I found mentions of this problem from other users of Prokka (https://github.com/tseemann/prokka/issues/139), apparently tbl2asn has to be downloaded again every year to be able to run!
Do you think it would it be possible to fix this in the singularity image? Thanks a lot!

Jasmine

**Comment by asetGem** [comment]
Hello,

Sure, I will do this when I'm back from my holidays. I precisely planned to update the image as I just came across the same error. 
Thanks for pointing out the fact that it is due to tbl2asn expiring after a year! So, I guess it expired a short time ago.

**Comment by JasmineGamblin** [comment]
Thank you so much!

**Comment by asetGem** [comment]
Hi,
Can you tell me if it works with the new panacota:latest image?

**Comment by JasmineGamblin** [comment]
Hi! I am currently running the annotate step and it's working! Thank you for the update :) I'll post again when my run is finished.

**Comment by JasmineGamblin** [comment]
(I'm sorry I didn't post earlier) I successfully ran all panacota modules and had no problem with 1.2.0 version!
