### ISSUE TITLE
The prepare step misses genomes

### ISSUE THREAD

**Issue by RedSnail** [gem-pasteur/PanACoTA#20]
Hello everyone, I've noticed that the prepare step of PanACoTA misses genomes, for example it missed GCF_000013385.1 from RefSeq.Mabye it would be a helpful information that the record does not contain the genomic sequence, only link to GenBank CP000251.1 assembly, which has the full information.

**Comment by asetGem** [comment]
Hello,
I am not sure I understand. Did you ask for a specific strain (`-S` option) that you saw on refseq, but it returned nothing?

**Comment by RedSnail** [comment]
I asked for specific species (taxid 290397, Anaeromyxobacter dehalogenans) in `-s` option, and it returned nothing

**Comment by asetGem** [comment]
If you use the taxid you are giving here, for me, it downloads it.

`PanACoTA prepare -t 290397` downloads 1 genome: `GCF_000013385.1_ASM1338v1_genomic.fna`
