### ISSUE TITLE
L90 filtering

### ISSUE THREAD

**Issue by Sirbius** [gem-pasteur/PanACoTA#33]
Hi there,

I'm new to PanACoTA and already have an issue with the initial steps.
I already have my sequences downloaded (150 bacterial genomes, most of them as draft with many contigs and really high l90).
I want to keep all of them but If i try to change the parameters I always ends up with only 9 or 13 genomes..
This are the options:
`PanACoTA prepare --norefseq -d Fasta-renamed/ --nbcont 1999 -o prepare --l90 100 --cutn 0`

If I try to change the l90 to 1600 (since from the discarded file this is the highest value I got), I get an error:
`Genomes compared:                                0/152 Elapsed Time: 0:00:00 - Traceback (most recent call last):
  File "/home/silviat/.local/bin/PanACoTA", line 8, in <module>
    sys.exit(main())
  File "/home/silviat/.local/lib/python3.6/site-packages/PanACoTA/bin/run_panacota.py", line 56, in main
    action(args)
  File "/home/silviat/.local/lib/python3.6/site-packages/PanACoTA/subcommands/prepare.py", line 73, in main_from_parse
    arguments.max_dist, arguments.verbose, arguments.quiet)
  File "/home/silviat/.local/lib/python3.6/site-packages/PanACoTA/subcommands/prepare.py", line 275, in main
    min_dist, max_dist, threads, quiet)
  File "/home/silviat/.local/lib/python3.6/site-packages/PanACoTA/prepare_module/filter_genomes.py", line 234, in iterative_mash
    mash_step(to_try, corresp_file, mat_sp, genomes_removed, min_dist, max_dist)
  File "/home/silviat/.local/lib/python3.6/site-packages/PanACoTA/prepare_module/filter_genomes.py", line 391, in mash_step
    dist = mat_sp[ref_num, other_num]
  File "/usr/local/lib64/python3.6/site-packages/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "/usr/local/lib64/python3.6/site-packages/scipy/sparse/_index.py", line 143, in _validate_indices
    raise IndexError('column index (%d) out of range' % col)
IndexError: column index (13) out of range
[silviat@marvin Psa-filtered]$ PanACoTA prepare --norefseq -d Fasta-renamed/ --nbcont 1999 -o prepare --l90 20 --cutn 0 
`

How can I avoid this? 
Plus, I already have Prokka annotations, can I skip also this step?
Thank you
Silvia

**Comment by asetGem** [comment]
Hi,

I'm very sorry for the delay!

For your first issue, could you please send me the output `.log` file of the first command line (`PanACoTA prepare --norefseq -d Fasta-renamed/ --nbcont 1999 -o prepare --l90 100 --cutn 0`) ?
Then, for the error you have, did you run `PanACoTA prepare --norefseq -d Fasta-renamed/ --nbcont 1999 -o prepare --l90 1600 --cutn 0` or did you change something else?

For your second question, if you already have prokka annotations, and you want to keep all your genomes whatever their quality, then you do not need to run the `prepare` module!

Check that your proteins files (the multifasta  `.faa` files generated by prokka) follow the requirements here: https://aperrin.pages.pasteur.fr/pipeline_annotation/html-doc/usage.html#protein-files.
If you annotated with prokka, it should be the case. Usually, it gives you headers like 
`>ACALPFMM_00006 HTH-type transcriptional regulator HdfR`
Then, the file containing this protein should be called `ACALPFMM.prt` (genome name is ACALPFMM).

Put all these `prt` files in the same directory, and directly run the `pangenome` module:

`PanACoTA pangenome -l <list_file> -n <dataset_name> -d <path/to/dbdir> -o <path/to/outdir> -i <min_id>`

Hope this can help. Do not hesitate to ask me for more details. Looking forward to your files to help you on the first issue.

AP
