### ISSUE TITLE
cpu count vs available cpus

### ISSUE THREAD

**Issue by EricDeveaud** [gem-pasteur/PanACoTA#37]
Hello,

`PanACoTA` uses `multiprocessing.cpu_count()` to ge the number of cpus via `utils_argparse.py`.
`multiprocessing.cpu_count()` return the number of cpu in the machine, But this is not the same as the number of cpu **available** to the process. For example, you can run in a taskset context or a batch scheduler like slurm.
NB `misc.py` also does the same
see:

```
$ nproc
96
$ taskset -c 1 nproc
1
$ taskset -c 1 python3 -c "import multiprocessing; print(multiprocessing.cpu_count())"
96
```
I would suggest to use len(os.sched_getaffinity(0)) instead of multiprocessing.cpu_count()
```
$ python3 -c "import os; print(len(os.sched_getaffinity(0)))"
96
$ taskset -c 1 python3 -c "import os; print(len(os.sched_getaffinity(0)))"
1
```
NB Mac OSX python does not have os.sched_getaffinity so a portable way to code it would be

```
try:
    num_cpus = len(os.sched_getaffinity(0))
except AttributeError:
    num_cpus = multiprocessing.cpu_count()
```

regards

Eric

**Comment by asetGem** [comment]
Thanks for your comment and your advices to solve this issue!

**Comment by EricDeveaud** [comment]
it would be nice (for consistency) to update the `test/test_functional/*` scripts that still use 
`nb_cpu = multiprocessing.cpu_count()`

regards

Eric

**Comment by asetGem** [comment]
I just updated them
