### ISSUE TITLE
Broken in conda with python > 3.6

### ISSUE THREAD

**Issue by psydvl** [gem-pasteur/PanACoTA#38]
If you'll try to install this package on conda with python at least 3.7 you'll face next error
```
Encountered problems while solving:
  - package panacota-1.3.1-pyhdfd78af_0 requires argparse, but none of the providers can be installed
```

Since anaconda not provide `argparse` package for python > 3.6
https://anaconda.org/conda-forge/argparse/files
https://anaconda.org/bioconda/argparse/files

Also, according to [`argparse` project description](https://pypi.org/project/argparse/) and python [documentation](https://docs.python.org/3/library/argparse.html), since python 3.2 `argparse` bundled in python standard library
And while minimal python version, `PanACoTA` required, is 3.4 `argparse` can be removed from requirements.txt so as bioconda's build receipt https://github.com/bioconda/bioconda-recipes/blob/70dd5a4b0a153ea1a015d38fbe1a75dc31a335f6/recipes/panacota/meta.yaml

**Comment by asetGem** [comment]
Thanks for letting me know. I updated the requirements.txt and I'll change the conda recipe as soon as possible.
