### ISSUE TITLE
Alignment fails when using gembase format

### ISSUE THREAD

**Issue by jeanrjc** [gem-pasteur/PanACoTA#39]
Hello,

When using Panacota on a gembase database, where the input file list contains sequences like `ACBA001.0122.000001.C001`, everything works well until the last part of the `align` module, where it groups alignments per genome. 

The problem is here : https://github.com/gem-pasteur/PanACoTA/blob/master/PanACoTA/utils.py#L552
Where it tries to convert C001 into an int, whereas it should take the previous field.

Replacing L552 of `utils.py` with 

```python
    if "." in x and len(x.split(".")) == 3:
        return x.split(".")[0], int(x.split(".")[-1])
    elif "." in x and len(x.split(".")) == 4:
        return x.split(".")[0], int(x.split(".")[-2])
```

solves the issue. 

Or maybe there is some other way to use panacota with genomes split per replicons (ACBA001.0122.000001.C001, ACBA001.0122.000001.P001, etc.) ?

Thanks

**Comment by asetGem** [comment]
Hi,

Gembase complete genomes format will soon be harmonized with the draft genome gembase format, meaning that the files won't have this `C001` anymore in their name. Like so, the current script will work as expected. 

I prefer not to consider soecifically genome names with 4 '.' separated fields. This could lead to other problems. To simplify, I advise to use either the gembase format (1 file per genome), either a genome name without dot (see https://aperrin.pages.pasteur.fr/pipeline_annotation/html-doc/usage.html#protein-files) and I modified the code accordingly.
That said, it will still work with your genome names. The only 'problem' is that strains might not be in the numerical order, but results won't change.
Try to use the head version and let me know if it works for you!
