### ISSUE TITLE
Choosing assembly level in `prepare` module

### ISSUE THREAD

**Issue by oxygen311** [gem-pasteur/PanACoTA#4]
### There are different assembly levels for genomes in ncbi:
<img src="https://user-images.githubusercontent.com/16215034/95650526-dfe7c480-0aec-11eb-8908-19859519681c.jpeg" alt="photo_2020-10-10 11 26 21" width="40%" height="40%">

Different researchers may need different assembly levels for their research. I suppose to add some feature to `prepare` module for filtering with the desired assembly level. 

Parameter example:  
`--assembly_level` parameter for tool, with the list of desired levels of assembly, e.g.: `--assembly_level chromosome,complete`.

**Comment by asetGem** [comment]
I now released version 1.0.1 where you can choose which assembly level(s) you want to download from NCBI.
Please, be free to try it, and tell me if it corresponds to what you were expecting.
