### ISSUE TITLE
running only formating of annotation step

### ISSUE THREAD

**Issue by aymericola** [gem-pasteur/PanACoTA#41]
Hello,
I used the command `PanACoTA all` on a big set of genes. 
The prepare command and the annotation went well. 
 `Annotation: ██████████████ 7284/7284 (100%) - Elapsed Time: 2 days, 11:07:00 - c`
But got a mistake 
`Formatting genomes: ███                1254/7284 ( 17%) - Elapsed Time: 0:00:15  * [2023-07-06 21:45:47] : ERROR  Wrong format for /home/resist/Documents/result_panacota/result_enterobacter_cloacae_complex/2-annotate_module/tmp_files/GCA_023152355.1_ASM2315235v1_genomic.fna_prepare-split5N.fna-prokkaRes/ENBU.0723.01261.gff.`

I eventualy figured out that it was because I didn't have enough space left after the creation of temp files (~ 410GB).
I cleaned my storage to make room for the rest of the results. As you can expect, I'd prefere not to run the whole annotation again.
While consulting the error I figured out there was a formating function called format_prokka.py in the PanACoTA
`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/resist/.local/lib/python3.10/site-packages/PanACoTA/annotate_module/general_format_functions.py", line 210, in handle_genome
    ok_format = format_one_genome(gpath, name, annot_path, lst_dir,
  File "/home/resist/.local/lib/python3.10/site-packages/PanACoTA/annotate_module/format_prokka.py", line 134, in format_one_genome
    ok_tbl = tbl2lst(prokka_tbl_file, res_lst_file, contigs, name, fna_file)
  File "/home/resist/.local/lib/python3.10/site-packages/PanACoTA/annotate_module/format_prokka.py", line 326, in tbl2lst
    lstline = general.write_gene(feature_type, locus_num,
  File "/home/resist/.local/lib/python3.10/site-packages/PanACoTA/annotate_module/general_format_functions.py", line 265, in write_gene
    lstopenfile.write(lst_line + "\n")
`
I already have the complete tmp_files folder. 
I know a bit of python, so I was wondering if it was possible to run only the formatting process using a python script to avoid redoing the whole annotation ? If so, How could I do it ?
Thanks in advance,
Aymeric.

**Comment by aymericola** [comment]
Okay since big studies takes a lot of storage, someone might run into this pb again. 
Hence I put here the short script I wrote to solve this issue without having to run the annotation again. 

```
import PanACoTA
from PanACoTA import annotate_module
from PanACoTA.annotate_module import general_format_functions

list_for_dic='/home/resist/Documents/result_panacota/2-annotate_module/LSTINFO-LSTINFO-NA-filtered-0.0_1.0.lst'

genomes_ok={}


with open(list_for_dic, "r") as file:	
    file.readline()
    for line in file:
        line = line.strip().split("\t")
        name = line[0]
        genomes_ok[f'{name}']=line[1:]
        
res_path='/home/resist/Documents/result_panacota/2-annotate_module'
annot_path='/home/resist/Documents/result_panacota/2-annotate_module/tmp_files'

PanACoTA.annotate_module.general_format_functions.format_genomes(genomes_ok, res_path, annot_path, prodigal_only=False, threads=8, quiet=False)
```

where:
`list_for_dic` is the directory of the LSTINFO file providing the following informations : orig_name, to_annotate, gsize, nb_conts & L90.
`res_path` is the directory of the place you want the following folders to be created : Genes, gff3, LSTINFO, Proteins & Replicons.
`annot_path` is the directory where prokka stored its results. 

source : 
[panacota python API website](https://aperrin.pages.pasteur.fr/pipeline_annotation/html-doc/PanACoTA.annotate_module.html)

In hope it'll help someone someday. 
Aymeric.

**Comment by asetGem** [comment]
Hi!

That should be already the case. While running annotation step, PanACoTA looks at the prokka (or prodigal) output directory, and only runs annotation if the expected output files are not already there. If you already ran the annotation before, it will skip the already annotated genomes, and only annotate the missing ones. Of course, this is provided that you use the same output directory, and that prokka/prodigal outputs are in <results>/tmp_files. But if you run the same command line after cleaning your storage, that should be fine.

For instance, if you run twice the toy dataset:
```
[2023-07-10 10:21:26] :: INFO :: Annotating all genomes with prodigal
[2023-07-10 10:21:26] :: DETAIL :: Start annotating GENO.0723.00001 (from Examples/2-res-prodigal/tmp
_files/genome1.fst_prodigal-split5N.fna sequence) with Prodigal
[2023-07-10 10:21:26] :: WARNING :: Prodigal results folder Examples/2-res-prodigal/tmp_files/genome1
.fst_prodigal-split5N.fna-prodigalRes already exists.
[2023-07-10 10:21:26] :: DETAIL :: Prodigal did not run again. Formatting step will use already gener
ated results of Prodigal in Examples/2-res-prodigal/tmp_files/genome1.fst_prodigal-split5N.fna-prodig
alRes. If you want to re-run Prodigal, first remove this result folder, or use '-F' or '--force' opti
on.
[2023-07-10 10:21:26] :: DETAIL :: End annotating GENO.0723.00001 (from Examples/2-res-prodigal/tmp_f
iles/genome1.fst_prodigal-split5N.fna)
[2023-07-10 10:21:26] :: DETAIL :: Start annotating GENO.1216.00002 (from Examples/2-res-prodigal/tmp
_files/genome3-chromo.fst-all.fna_prodigal-split5N.fna sequence) with Prodigal
[2023-07-10 10:21:26] :: WARNING :: Prodigal results folder Examples/2-res-prodigal/tmp_files/genome3
-chromo.fst-all.fna_prodigal-split5N.fna-prodigalRes already exists.
[2023-07-10 10:21:26] :: DETAIL :: Prodigal did not run again.
[...]
```

**Comment by aymericola** [comment]
Hi, great point, thanks for your answer. 
I did not notice that!
best,
Aymeric.
