### ISSUE TITLE
PanACoTA prepare command download from NCBI error

### ISSUE THREAD

**Issue by lear-711** [gem-pasteur/PanACoTA#42]
Hello!
When I run the command `PanACoTA prepare -g "Acinetobacter baumannii" -l complete` (or with another bacteria names) there is error: "No strain correspond to your request"

Log of command run:
```
$ PanACoTA prepare -g "Acinetobacter baumannii" -l complete
  !! Your genomes will be split when sequence contains at least 5'N' in a row. If you want to change this threshold, use '--cutn n' option (n=0 if you do not want to cut)
  !! Your genomes will be filtered, and only the ones with 'L90' <= 100 and 'number of contigs' < 999 will be kept. If you want to change those thresholds, use '--l90' and '--nbcont' options.
  * [2023-09-02 18:52:51] : INFO  PanACoTA version 1.4.0
  * [2023-09-02 18:52:51] : INFO  Command used
   > PanACoTA prepare -g Acinetobacter baumannii -l complete
  * [2023-09-02 18:52:51] : INFO  'PanACoTA prepare' will run on 1 core
  * [2023-09-02 18:52:51] : INFO  Metadata for all genomes will be saved in Acinetobacter_baumannii/assembly_summary-Acinetobacter_baumannii.txt
  * [2023-09-02 18:52:51] : INFO  From refseq: Downloading all genomes of NCBI species = Acinetobacter baumannii (Only those assembly levels: complete). 
  * [2023-09-02 18:53:07] : ERROR  No strain correspond to your request. If you are sure there should have some, check that you gave valid NCBI taxid and/or NCBI species name and/or NCBI strain name. If you gave several, check that given taxIDs and names are compatible.
```
This bug was caused by change of response format from NCBI (ncbi_genome_download lib). In requirements it's specified as follows:
```
ncbi_genome_download >= 0.3.0
```

In ncbi_genome_download v. 0.3.3 bug was fixed. 
Please bump an update of the following lib in requirements.txt:
```
ncbi_genome_download >= 0.3.3
```

**Comment by asetGem** [comment]
Hi,
Thanks for letting me know. This has been changed for the last version of master, and will be integrated in the next release.

**Comment by octolis** [comment]
Hello! I use singularity container with the latest version of panacota. I faced the same issue. When I run
`./panacota.img prepare -T 104099 -g "Acetobacter orleanensis"`

I get an error: 
`ERROR :: No strain correspond to your request. If you are sure there should have some, check that you gave valid NCBI taxid and/or NCBI species name and/or NCBI strain name. If you gave several, check that given taxIDs and names are compatible.`

Probably `ncbi_genome_download` has not been updated in the container? What can I do to overcome the issue? Thanks!
