### ISSUE TITLE
>mash sketch error

### ISSUE THREAD

**Issue by sujeetpowar** [gem-pasteur/PanACoTA#43]
Hi,
I was trying to run a panacota on a test genomes and I encountered with this error. Could you please help me with it?
"error: command '>mash sketch -o 481145/mash_files/all-genomes-481145 -p 1 -l 481145/mash_files/list-to-sketch-481145.txt -s 1e4' is not possible".

I have also attached the log file if you need.
[PanACoTA_prepare_481145.log](https://github.com/gem-pasteur/PanACoTA/files/13559610/PanACoTA_prepare_481145.log)
Please let me know how to fix this error.

Thank you for your help!

**Comment by asetGem** [comment]
Hi,

That could be for many reasons...
Can you type in the command `mash sketch -o 481145/mash_files/all-genomes-481145 -p 1 -l 481145/mash_files/list-to-sketch-481145.txt -s 1e4` and let me know the output please?

**Comment by sujeetpowar** [comment]
Hi,
Sorry for my late reply. I no longer have this error after I installed mash separately. But I have other problem with the annotation. Can I share it in this thread or do I have to create a new one?

**Comment by sujeetpowar** [comment]
Hi, never mind. I could run the panacota without any issues. Thank you for your help.
