### ISSUE TITLE
Could not determine version of cmpress - please install version 1.1 or higher

### ISSUE THREAD

**Issue by octolis** [gem-pasteur/PanACoTA#46]
I'm currently utilizing the Singularity container for PanACoTA v1.2.0. Using `annotate` on LSTINFO files, I received some annotations. However, reviewing the log files, I noticed errors (example below):
 
<img width="1280" alt="image" src="https://github.com/gem-pasteur/PanACoTA/assets/46808738/571d7bd5-7c62-4525-a6ff-ceddfbbae618">

I suppose the problem is that prokka can't find cmpress from Infernal. This is critical for me as I require T-box non-coding RNAs to be annotated. However, given that I'm using a container, I'm uncertain about how to resolve this issue. I would greatly appreciate any advice on how to address this issue.

Thank you in advance!

**Comment by aperrin** [comment]
Hi, sorry for the delay. This problem is now solved with the last version of the container. You can pull panacota:latest singularity container, and cmpress should be found.
Let me know if it does not !
