### ISSUE TITLE
Combining genomes from several sources in one analysis

### ISSUE THREAD

**Issue by IsabelFE** [gem-pasteur/PanACoTA#5]
I am trying to combine different genomes from different sources together in the analysis and I am not sure who I should do it.  I have a collection of genomes from 94 _Corynebacterium_ isolates that based on preliminar 16S analysis belong to 7 _Corynebacterium_ species. I want to tree all of them following your pipeline (and later made species level pangenome analysis once we fully define what isolates belong to each species). 
I've used `PanACoTA prepare -s "Corynebacterium xxxx"` for the 7 species, and also `PanACoTA prepare --norefseq -d "Isolates"` for my own genomes. So now I have several LSTINFO_FILE files and genomes in several folders. How I annotate (is renaming required?) and combine everything in a single analysis? Should I use `PanACoTA annotate` in each individual folder and later combine at the `PanACoTA pangenome` step? I am not sure if any of those commands can take more than one LSTINFO_FILE and -d DBPATH at once.
Thanks!

**Comment by asetGem** [comment]
I think there are 2 ways to do that.

The first one is to merge all your lstinfo files into one, and give this as an input to annotate module. This will annotate and format all your genomes, even if they are not all in the same folder. The only thing is that they will be all renamed with the same 'name' (option -n name). This means that, let's say that you put -n NCBI as parameter, then you will have all your genomes called NCBI.date.strain_number. But, of course, you will still have a file with corresponding original and formatted names.

The second way, if you need to put different names for each LSTINFO content, is to run annotate on each one, giving each time a different '-n name'. Then, you will be able to give all genomes to the next steps (pangenome etc.)

Hope it will help you! And do not hesitate to ask if this is not clear

**Comment by IsabelFE** [comment]
I am trying the second method, so I can keep the genome names. I ended up with 8 different folders as output from the annotation step: 6 _Corynebacterium_ species from NCBI, plus 2 sets of assemblies for our _Corynebacterium_ strains (a set sequences at NIH and another at the Broad).
So I concatenate all LSTINFO-LSTINFO files in one file named `LSTINFO-Corynes_2020_1019.txt`

```{bash, eval=FALSE}
mkdir Pangenome
cat "LSTINFO-LSTINFO-Corynebacterium_accolens-filtered-0.0001_0.06.txt"
"LSTINFO-LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.txt"
"LSTINFO-LSTINFO-Corynebacterium_macginleyi-filtered-0.0001_0.06.txt"
"LSTINFO-LSTINFO-Corynebacterium_propinquum-filtered-0.0001_0.06.txt"
"LSTINFO-LSTINFO-Corynebacterium_pseudodiphtheriticum-filtered-0.0001_0.06.txt"
"LSTINFO-LSTINFO-Corynebacterium_tuberculostearicum-filtered-0.0001_0.06.txt"
"Genomes_KPL_Broad/Broad_Annotated/LSTINFO-LSTINFO-NA-filtered-0.0_1.0.lst" 
"Genomes_KPL_JASHHK/JASHHK_Annotated/LSTINFO-LSTINFO-NA-filtered-0.0_1.0.lst" > Pangenome/LSTINFO-Corynes_2020_1019.txt
```

Then I tried:
```
PanACoTA pangenome -l "Pangenome/LSTINFO-Corynes_2020_1019.lst" -n Corynes_2020_1019 -o "Pangenome"
```

And realized that I need to provide a folder with the protein sequences output of the annotation step. Can this be provided as a list file with several locations? Or should I just merge the 8 individual `Protein` folders in one.

**Comment by IsabelFE** [comment]
I think that I found the way to do it:

I create a concatenated file with the LSTINFO-LSTINFO from all the annotation folders:
```
mkdir Pangenome
cat "Genomes_NCBI/Annotated_Cacc/LSTINFO-LSTINFO-Corynebacterium_accolens-filtered-0.0001_0.06.lst" "Genomes_NCBI/Annotated_Cbov/LSTINFO-LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.lst" "Genomes_NCBI/Annotated_Cmac/LSTINFO-LSTINFO-Corynebacterium_macginleyi-filtered-0.0001_0.06.lst" "Genomes_NCBI/Annotated_Cpro/LSTINFO-LSTINFO-Corynebacterium_propinquum-filtered-0.0001_0.06.lst" "Genomes_NCBI/Annotated_Cpse/LSTINFO-LSTINFO-Corynebacterium_pseudodiphtheriticum-filtered-0.0001_0.06.lst" "Genomes_NCBI/Annotated_Ctub/LSTINFO-LSTINFO-Corynebacterium_tuberculostearicum-filtered-0.0001_0.06.lst" "Genomes_KPL_Broad/Broad_Annotated/LSTINFO-LSTINFO-NA-filtered-0.0_1.0.lst" "Genomes_KPL_JASHHK/JASHHK_Annotated/LSTINFO-LSTINFO-NA-filtered-0.0_1.0.lst" > Pangenome/LSTINFO-Corynes_2020_1019.txt
```

I copy all the protein files from all the annotation folders into one:
```
mkdir Pangenome/Proteins
find . -type f -name "*.prt" -exec cp {} "Pangenome/Proteins/" \;
```

Finally I run the Pangenome:
```
PanACoTA pangenome -l "Pangenome/LSTINFO-Corynes_2020_1019.txt" -n Corynes_2020_1019 -o "Pangenome/Pangenome_Corynes_2020_1019" -d "Pangenome/Proteins"
```

**Comment by asetGem** [comment]
Yes, this should work. Also, you could simply, when you did your different 8 Panacota annotate commands, give always the same output directory. Hence, all prt files will be in a same Proteins directory (as well as all .gen in Genes directory etc., which will be useful for the next steps).

**Comment by IsabelFE** [comment]
Thanks, that is good to know. I encountered the issue with the Genes directory already and also move them the same way. I already have the alignment, so I am getting really close to the end of the pipeline!! Thanks for all your help, this is a really neat pipeline and for sure we are going to be using it a lot in the future :)
